export default {
  login: 'kailash360',
  id: 75155230,
  node_id: 'MDQ6VXNlcjc1MTU1MjMw',
  avatar_url: 'https://avatars.githubusercontent.com/u/75155230?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/kailash360',
  html_url: 'https://github.com/kailash360',
  followers_url: 'https://api.github.com/users/kailash360/followers',
  following_url:
    'https://api.github.com/users/kailash360/following{/other_user}',
  gists_url: 'https://api.github.com/users/kailash360/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/kailash360/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/kailash360/subscriptions',
  organizations_url: 'https://api.github.com/users/kailash360/orgs',
  repos_url: 'https://api.github.com/users/kailash360/repos',
  events_url: 'https://api.github.com/users/kailash360/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/kailash360/received_events',
  type: 'User',
  site_admin: false,
  name: 'Kailash Kejriwal',
  company: 'IIIT Gwalior',
  blog: 'kailashk.me',
  location: 'Suri, West Bengal',
  email: null,
  hireable: null,
  bio: "GSoC'22 @EOS-uiux-Solutions | MERN | Blockchain | Technical Content Writer ",
  twitter_username: 'KailashK360',
  public_repos: 73,
  public_gists: 1,
  followers: 100,
  following: 147,
  created_at: '2020-11-28T05:40:18Z',
  updated_at: '2022-12-21T09:37:00Z',
}
